In [2]:
from scipy import stats 
import numpy as np 
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size = 100 , random_state = rng)
sample2 = stats.norm.rvs(size = 110 , random_state = rng)
response =stats.ks_2samp(sample1,sample2)

In [3]:
sample1

array([0.02443015, 0.71785372, 0.89399519, 0.0117814 , 0.86220254,
       0.56991331, 0.01650955, 0.3536112 , 0.2298996 , 0.50685633,
       0.95201579, 0.43988565, 0.09194685, 0.49439135, 0.44512281,
       0.90937996, 0.36222487, 0.40022972, 0.58503541, 0.61570251,
       0.36669151, 0.47009041, 0.48037595, 0.25360998, 0.83114999,
       0.81076208, 0.8331824 , 0.44240647, 0.52483263, 0.43592268,
       0.34177632, 0.53934908, 0.00786192, 0.39302007, 0.57103234,
       0.68498692, 0.15690752, 0.18899324, 0.94831509, 0.93593944,
       0.1096263 , 0.71511687, 0.83962261, 0.00203196, 0.08456176,
       0.38198643, 0.40136086, 0.75459565, 0.01065402, 0.38842621,
       0.00662265, 0.61180259, 0.67891122, 0.49881393, 0.48656223,
       0.98442605, 0.95928434, 0.01538969, 0.7779802 , 0.416437  ,
       0.25730973, 0.94509239, 0.66030978, 0.99651409, 0.45700615,
       0.00509265, 0.42106771, 0.526158  , 0.9971069 , 0.76559687,
       0.00396301, 0.34747535, 0.31760846, 0.40837155, 0.39570

In [4]:
sample2

array([-0.73834931, -0.59953499, -0.59974741, -0.33489882, -0.67724017,
        0.258885  , -0.6901832 , -0.11683456, -1.34833056, -0.23409023,
       -1.73495569,  0.09370233, -0.0740702 , -0.91331828, -0.88878361,
       -0.64607051,  0.50952511, -0.16732598, -1.85457296,  0.64845574,
        1.05416639, -1.36240344, -0.14498403, -0.59913172, -1.76172732,
        1.25716516,  1.15415089, -0.25770034, -0.38978687, -1.8309688 ,
       -0.78653925, -0.74691635,  1.08399966,  0.87285616,  0.27137682,
       -0.58122004, -0.52629425,  0.55729204,  1.75161746,  0.61152084,
        1.54512033,  0.84506294, -1.16459541, -0.08856572,  0.30531932,
        0.19306407,  0.73089589,  0.00275687,  0.40367314,  0.40695322,
       -1.10678963,  0.56013046, -0.64797419, -1.87798957,  0.51862665,
       -0.72207585,  1.28814284,  0.72102924, -0.87642605, -0.38336582,
        1.41975327,  0.78397699,  1.25247213,  1.96763461,  1.1012997 ,
       -1.27425858, -0.12496131,  1.17178534,  1.47617882,  1.01

In [5]:
response.pvalue

2.1983365627813573e-13

In [1]:
import pandas as pd 

In [2]:
df=pd.read_csv("/config/workspace/artifact/02202023__122931/data_ingestion/dataset/train.csv")

In [5]:
df.isnull().sum().sum()

414077

In [7]:
df.isnull().sum()

class         0
aa_000        0
ab_000    22358
ac_000     1723
ad_000     7413
          ...  
ee_007      305
ee_008      305
ee_009      305
ef_000     1398
eg_000     1397
Length: 171, dtype: int64

In [9]:
df.isnull().sum()/df.shape[0]

class     0.000000
aa_000    0.000000
ab_000    0.772297
ac_000    0.059516
ad_000    0.256062
            ...   
ee_007    0.010535
ee_008    0.010535
ee_009    0.010535
ef_000    0.048290
eg_000    0.048256
Length: 171, dtype: float64

In [11]:
(df.isnull().sum()/df.shape[0]).values

array([0.        , 0.        , 0.77229706, 0.05951641, 0.25606218,
       0.04431779, 0.04431779, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01098446, 0.01074266, 0.01074266,
       0.0784456 , 0.01088083, 0.01074266, 0.01088083, 0.00974093,
       0.01088083, 0.00974093, 0.04825561, 0.01074266, 0.01074266,
       0.01074266, 0.04435233, 0.04435233, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01074266, 0.01074266,
       0.01074266, 0.01074266, 0.01074266, 0.01074266, 0.01074266,
       0.01074266, 0.01074266, 0.01074266, 0.01098446, 0.04829016,
       0.04829016, 0.04438687, 0.04431779, 0.01088083, 0.01088083,
       0.00974093, 0.00974093, 0.37920553, 0.44770294, 0.65274

In [12]:
(df.isnull().sum()/df.shape[0]).index

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [14]:
for column_name ,missing_percentage in zip((df.isnull().sum()/df.shape[0]).index , (df.isnull().sum()/df.shape[0]).values):
    print(column_name,missing_percentage*100)

class 0.0
aa_000 0.0
ab_000 77.22970639032816
ac_000 5.951640759930915
ad_000 25.606217616580313
ae_000 4.431778929188256
af_000 4.431778929188256
ag_000 1.0535405872193437
ag_001 1.0535405872193437
ag_002 1.0535405872193437
ag_003 1.0535405872193437
ag_004 1.0535405872193437
ag_005 1.0535405872193437
ag_006 1.0535405872193437
ag_007 1.0535405872193437
ag_008 1.0535405872193437
ag_009 1.0535405872193437
ah_000 1.0984455958549224
ai_000 1.07426597582038
aj_000 1.07426597582038
ak_000 7.844559585492227
al_000 1.0880829015544042
am_0 1.07426597582038
an_000 1.0880829015544042
ao_000 0.9740932642487047
ap_000 1.0880829015544042
aq_000 0.9740932642487047
ar_000 4.825561312607944
as_000 1.07426597582038
at_000 1.07426597582038
au_000 1.07426597582038
av_000 4.435233160621762
ax_000 4.435233160621762
ay_000 1.0535405872193437
ay_001 1.0535405872193437
ay_002 1.0535405872193437
ay_003 1.0535405872193437
ay_004 1.0535405872193437
ay_005 1.0535405872193437
ay_006 1.0535405872193437
ay_007 1.0535

In [16]:
drop_column_name =[]
for column_name ,missing_percentage in zip((df.isnull().sum()/df.shape[0]).index , (df.isnull().sum()/df.shape[0]).values):
    #print(column_name,missing_percentage*100)
    if missing_percentage*100 >30:
        drop_column_name.append(column_name)

In [20]:
drop_column_name

['ab_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'cr_000']

In [28]:
null_report = df.isnull().sum()/df.shape[0]
null_report[null_report>.3].index

Index(['ab_000', 'bk_000', 'bl_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000',
       'bq_000', 'br_000', 'cr_000'],
      dtype='object')

In [32]:
df.drop(list(drop_column_name),axis=1,inplace=True)

In [33]:
drop_column_name

['ab_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'cr_000']

In [41]:
len(df.iloc[:,[0]].drop("class",axis=1).columns)

0